version: '3.8'

services:
  auth-service:
    build:
      context: ../trip-planner-auth-service/TripPlanner.AuthService
    ports:
      - "8081:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=trip_planner;Username=postgres;Password=postgres"
    depends_on:
      - postgres

  trip-service:
    build:
      context: ../trip-planner-trip-service/TripPlanner.TripService
    ports:
      - "8082:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=trip_planner;Username=postgres;Password=postgres"
    depends_on:
      - postgres

  itinerary-service:
    build:
      context: ../trip-planner-itinerary-service/TripPlanner.ItineraryService
    ports:
      - "8083:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=trip_planner;Username=postgres;Password=postgres"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: trip-planner-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trip_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: trip-planner-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tripplanner.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  portainer:
    image: portainer/portainer-ce:latest
    container_name: trip-planner-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  kong:
    image: kong:3.7
    container_name: trip-planner-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./kong-compose.yml:/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - auth-service
      - trip-service
      - itinerary-service

  prometheus:
    image: prom/prometheus
    container_name: trip-planner-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kong

  grafana:
    image: grafana/grafana
    container_name: trip-planner-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  frontend:
    build:
      context: ../trip-planner-frontend
    ports:
      - "5173:80"
    depends_on:
      - kong

volumes:
  postgres_data:
  portainer_data: